version: 2
updates:
    # Keep npm dependencies up to date
    - package-ecosystem: "npm"
      directory: "/"
      target-branch: main
      schedule:
          interval: "weekly"
          time: "00:00"
          timezone: "Australia/Sydney"
      pull-request-branch-name:
          separator: "-"
      labels:
          - "Dependabot"
