name: Merge dependabot pr
on: pull_request_target

permissions:
    pull-requests: write
    contents: write

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v1
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

            - name: Approve PR
              run: gh pr review --approve "$PR_URL"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PR_URL: ${{ github.event.pull_request.html_url }}

            - name: Enable auto-merge for Dependabot PRs
              run: gh pr merge --auto --squash "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
